# 头像设置
avatar:
  img: /img/avatar.jpg
  effect: false  # 关闭头像旋转

# 网站标题
site_title_font:
  font_family: 'ZhuZiAWan, "Noto Serif SC", serif'
  font_size: 2.5rem
  font_weight: bold
  color: "#ffffff"
  text_align: center
  text_shadow: '2px 2px 4px #000000'

# 网站副标题
site_subtitle_font:
  font_family: 'ZhuZiAWan, "Noto Serif SC", serif'
  font_size: 1.5rem
  font_weight: bold
  color: "#ffffff"
  text_align: center
  text_shadow: '2px 2px 4px #000000'

# 背景设置
# background: '/img/background.jpg'
background_overlay: true
background_color: rgba(0, 0, 0, 0.5)

# 鼠标点击效果
cursor:
  enable: true
  type: 'fireworks'  # 烟花特效

# 页面效果
page_animations: true
page_transitions: true

# 社交图标
social:
  fab fa-github: https://github.com/Novicenew || Github || "#ffffff"

# 首页文章显示
index_post_content:
  enable: true
  length: 300

# 文章页面配置
post_meta:
  page:
    date_type: created
    categories: true
    tags: true

# 侧边栏设置
card_author:
  enable: true
  description: 纵使杯水车薪，我亦在所不惜

# 分类系列功能
category_ui: 
  enable: true

# 导航菜单
menu:
  首页: / || fas fa-home
  分类: /categories/ || fas fa-folder-open
  标签: /tags/ || fas fa-tags
  归档: /archives/ || fas fa-archive
  关于: /about/ || fas fa-heart

# 首页封面大图
index_img: /img/background.jpg 