# 头像设置
avatar:
  img: /img/avatar.jpg
  effect: false  # 关闭头像旋转

# 网站标题和副标题设置
subtitle:
  enable: true
  effect: false  # 关闭打字机特效
  loop: false
  source: false
  sub:
    - 纵有疾风起，人生不言弃

# 网站标题
site_title_font:
  font_family: 'Aa牡丹亭毛笔行书, "华文行楷", STXingkai, cursive'
  font_size: 4rem
  font_weight: normal
  color: "#ffffff"
  text_align: center
  text_shadow: '2px 2px 4px rgba(0, 0, 0, 0.3)'

# 网站副标题
site_subtitle_font:
  font_family: 'Aa牡丹亭毛笔行书, "华文行楷", STXingkai, cursive'
  font_size: 2.5rem
  font_weight: normal
  color: "#ffffff"
  text_align: center
  text_shadow: '2px 2px 4px rgba(0, 0, 0, 0.3)'

# 背景设置
# background: '/img/background.jpg'
background_overlay: true
background_color: rgba(0, 0, 0, 0.5)

# 鼠标点击效果
cursor:
  enable: true
  type: 'fireworks'  # 烟花特效

# 页面效果
page_animations: true
page_transitions: true

# 社交图标
social:
  fab fa-github: https://github.com/Novicenew || Github || "#ffffff"

# 首页文章显示
index_post_content:
  enable: false

# 文章页面配置
post_meta:
  page:
    date_type: created
    categories: true
    tags: true

# 侧边栏设置
card_author:
  enable: true
  description: 纵使杯水车薪，我亦在所不惜

# 分类系列功能
category_ui: 
  enable: true
  layout: block
  sort: true
  description: true

# 导航菜单
menu:
  分类: /categories/ || fas fa-folder-open
  标签: /tags/ || fas fa-tags
  归档: /archives/ || fas fa-archive
  关于: /about/ || fas fa-heart

# 首页封面大图
index_img: /img/background.jpg

# 首页分类卡片设置
categoryBar:
  enable: true
  style: card
  color: true
  sort: true
  animation: true
  description: true

# 分类页面设置
category_page:
  enable: true
  layout: category
  subtitle: 
  order_by: name
  top_img: /img/category-bg.jpg

# 注入自定义样式
inject:
  head:
    - <link rel="stylesheet" href="/css/custom.css">
  bottom:
    - <script src="/js/cursor-effects.js"></script>
    - <script src="/js/category-cards.js"></script> 